.TH MEEP 1 "November 18, 2006" "meep" "meep"
.SH NAME
meep \- finite-difference time-domain simulations
.SH SYNOPSIS
.B meep
[options] [definitions] [ctl files]
.br
.SH DESCRIPTION
\fBmeep\fP is a free finite-difference time-domain (FDTD) simulation software
package developed at MIT to model electromagnetic systems.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-V, \-\-version
Show version of program.
.TP
.B \-v, \-\-verbose
Enable verbose output.
.TP
.B \-\-spec\-file=<file>
Use <file> for spec. file.
.SH DEFINITIONS
Assignements of the form <variable>=<value>
.SH CONTROL FILES
Zero or more Scheme/ctl files to execute.
.SH AUTHOR
meep was written by Steven G. Johnson <stevenj@alum.mit.edu>.
.PP
This manual page was written by Loic Le Guyader <loic.leguyader@laposte.net>,
for the Debian project (but may be used by others).
